spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storedb
    username: app_user
    password: userpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/storedb
    user: flyway_user
    password: flywaypw
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always